from django.urls import path
from django.shortcuts import redirect
from . import views

urlpatterns = [
    path('', lambda request: redirect('login'), name='root'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('about/', views.about_view, name='about'),
    path('about/edit/<int:about_id>/', views.edit_about_view, name='edit_about'),
    path('skills/', views.skills_view, name='skills'),
    path('skills/edit/<int:skill_id>/', views.edit_skills_view, name='edit_skills'),
    path('services/', views.services_view, name='services'),
    path('portfolio/', views.portfolio_view, name='portfolio'),
    path('portfolio/edit/<int:portfolio_id>/', views.edit_portfolio_view, name='edit_portfolio'),
    path('qualifications/', views.qualifications_view, name='qualifications'),
    path('qualifications/edit/<int:qualification_id>/', views.edit_qualifications_view, name='edit_qualifications'),
    path('testimonials/', views.testimonials_view, name='testimonials'),
    path('testimonials/edit/<int:testimonial_id>/', views.edit_testimonials_view, name='edit_testimonials'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('index/', views.index_view, name='index'),
    path('index/<int:user_id>/', views.index_view, name='index_user'),
    path('api/register/', views.api_register, name='api_register'),
    path('api/login/', views.api_login, name='api_login'),
    path('api/about/', views.api_about, name='api_about'),
    path('api/about/edit/<int:about_id>/', views.api_edit_about, name='api_edit_about'),
    path('api/portfolio/', views.api_portfolio, name='api_portfolio'),
    path('api/portfolio/edit/<int:portfolio_id>/', views.api_edit_portfolio, name='api_edit_portfolio'),
    path('api/skills/', views.api_skills, name='api_skills'),
    path('api/skills/edit/<int:skill_id>/', views.api_edit_skills, name='api_edit_skills'),
    path('api/qualifications/', views.api_qualifications, name='api_qualifications'),
    path('api/qualifications/edit/<int:qualification_id>/', views.api_edit_qualifications, name='api_edit_qualifications'),
    path('api/services/', views.api_services, name='api_services'),
    path('api/services/edit/<int:service_id>/', views.api_edit_services, name='api_edit_services'),
    path('api/testimonials/', views.api_testimonials, name='api_testimonials'),
    path('api/testimonials/edit/<int:testimonial_id>/', views.api_edit_testimonials, name='api_edit_testimonials'),
    # Delete API endpoints
    path('api/about/delete/<int:about_id>/', views.api_delete_about, name='api_delete_about'),
    path('api/skills/delete/<int:skill_id>/', views.api_delete_skill, name='api_delete_skill'),
    path('api/qualifications/delete/<int:qualification_id>/', views.api_delete_qualification, name='api_delete_qualification'),
    path('api/services/delete/<int:service_id>/', views.api_delete_service, name='api_delete_service'),
    path('api/portfolio/delete/<int:portfolio_id>/', views.api_delete_portfolio, name='api_delete_portfolio'),
    path('api/testimonials/delete/<int:testimonial_id>/', views.api_delete_testimonial, name='api_delete_testimonial'),
    path('api/logout/', views.api_logout, name='api_logout'),
    path('api/dashboard/', views.dashboard_home, name='dashboard_home'),
    path('api/', views.public_index, name='public_index'),
    #path('api/api/portfolio/', views.public_index, name='public_index'),
] 